name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/inverse/multi-arch-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        if: startsWith(github.ref, 'refs/heads/master')
        name: Set image tag for master builds
        run: echo "REGISTRY_IMAGE_TAG=${{ env.REGISTRY_IMAGE }}:dev" >> $GITHUB_ENV
      -
        if: startsWith(github.ref, 'refs/tags/v')
        name: Set image tag for tagged builds
        run: echo "REGISTRY_IMAGE_TAG=${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }},${{ env.REGISTRY_IMAGE }}:latest" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ env.REGISTRY_IMAGE_TAG }}



